server.port=${PORT:8081}
spring.application.name=Email_backend

# BLUEHOST cPanel API CONFIG (For Creating Email Accounts via App Signup)
cpanel.host=${CPANEL_HOST:mail.botsuat.com}
cpanel.port=${CPANEL_PORT:2083}
cpanel.username=${CPANEL_USERNAME:YOUR_CPANEL_USERNAME}
cpanel.token=${CPANEL_TOKEN:YOUR_CPANEL_API_TOKEN}

accessmanager.base-url=${ACCESSMANAGER_BASE_URL:http://localhost:9086/accessmanager}
email.product-code=${EMAIL_PRODUCT_CODE:3}




spring.websocket.path=/chat
spring.websocket.allowed-origins=${SPRING_WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://15.206.148.49:5432/postgres?currentSchema=email_dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dev_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Dev@123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.pool-name=HikariPool-ChatApp
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.auto-commit=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Microsoft OAuth / ROPC Configurations
microsoft.oauth.client-id=${MICROSOFT_OAUTH_CLIENT_ID:04b47bff-348d-41d1-829a-f4276486e287}
microsoft.oauth.scope=${MICROSOFT_OAUTH_SCOPE:openid profile email https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send offline_access}
microsoft.oauth.domains=${MICROSOFT_OAUTH_DOMAINS:botsedge.ai}


